"""Static status page: one dark HTML file + chart PNGs, no JS, no backend.

Regenerated by cron after each daily load; served as plain files
(e.g. by Caddy under /fuel). Design: quiet dark chrome, monospace data,
one phosphor-green accent.
"""

from datetime import UTC, datetime, timedelta
from pathlib import Path

import matplotlib
import pandas as pd
from sqlalchemy import text

from pipeline.db.session import get_engine

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402  (backend must be set first)

PAGE = "#0d0d0d"
SURFACE = "#111110"
INK = "#e6e6e3"
MUTED = "#8a8a86"
GRID = "#262624"
BASE = "#383835"
ACCENT = "#00e65c"  # phosphor: UI accents only, never a data series
GREEN = "#00b34a"  # chart series, validated against the dark surface
BLUE = "#3987e5"
AMBER = "#fab219"
RED = "#e66767"

STALE_AFTER = timedelta(days=3)


def _chart_style() -> None:
    plt.rcParams.update({
        "figure.facecolor": SURFACE, "axes.facecolor": SURFACE,
        "savefig.facecolor": SURFACE, "savefig.dpi": 150, "savefig.bbox": "tight",
        "axes.edgecolor": BASE, "axes.grid": True, "grid.color": GRID,
        "axes.axisbelow": True, "text.color": INK, "axes.labelcolor": MUTED,
        "xtick.color": MUTED, "ytick.color": MUTED,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.spines.left": False, "font.family": "monospace", "font.size": 10,
        "axes.titlesize": 11, "axes.titleweight": "bold",
        "axes.titlelocation": "left", "legend.frameon": False,
    })


def _line_chart(df: pd.DataFrame, series: list[tuple[str, str, int]], title: str,
                out: Path) -> None:
    fig, ax = plt.subplots(figsize=(8.6, 3.4))
    for column, color, dy in series:
        line = df[column].dropna().astype(float)
        ax.plot(line.index, line, color=color, lw=1.8, label=column)
        ax.annotate(column, xy=(line.index[-1], line.iloc[-1]), xytext=(6, dy),
                    textcoords="offset points", color=color, fontweight="bold",
                    va="center")
    ax.set_title(title, color=INK)
    ax.set_ylabel("EUR / litre")
    ax.legend(loc="upper left", ncols=len(series))
    ax.margins(x=0.01)
    fig.savefig(out)
    plt.close(fig)


def _render_charts(engine, img_dir: Path) -> None:
    _chart_style()
    history = pd.read_sql(
        """SELECT price_date, category, price_eur FROM mart_price_history
           WHERE series = 'eu_bulletin' AND country = 'ES' ORDER BY price_date""",
        engine, parse_dates=["price_date"],
    ).pivot(index="price_date", columns="category", values="price_eur")
    history = history.rename(columns={"g95": "G95", "diesel": "Diesel"})
    _line_chart(history, [("G95", GREEN, 8), ("Diesel", BLUE, -8)],
                "SPAIN · WEEKLY SINCE 2005", img_dir / "history.png")

    vs_eu = pd.read_sql(
        """SELECT week, country, price_eur FROM mart_spain_vs_eu
           WHERE category = 'g95' AND country IN ('ES', 'EU')
             AND week >= (SELECT max(week) FROM mart_spain_vs_eu) - INTERVAL '3 years'
           ORDER BY week""",
        engine, parse_dates=["week"],
    ).pivot(index="week", columns="country", values="price_eur")
    _line_chart(vs_eu, [("ES", GREEN, 0), ("EU", BLUE, 0)],
                "G95 · SPAIN VS EU AVERAGE · 3Y", img_dir / "vs_eu.png")


def _query_state(engine) -> dict:
    with engine.connect() as conn:
        runs = conn.execute(text(
            """SELECT r.started_at, s.name, r.status, r.items_ok, r.items_failed
               FROM runs r JOIN sources s ON s.id = r.source_id
               ORDER BY r.id DESC LIMIT 8"""
        )).all()
        stations, points, days = conn.execute(text(
            """SELECT
                 (SELECT count(DISTINCT split_part(p.external_id, ':', 1))
                    FROM products p JOIN sources s ON s.id = p.source_id
                    WHERE s.name = 'fuel_es'),
                 (SELECT count(*) FROM price_snapshots),
                 (SELECT count(DISTINCT ps.collected_at)
                    FROM price_snapshots ps
                    JOIN products p ON p.id = ps.product_id
                    JOIN sources s ON s.id = p.source_id WHERE s.name = 'fuel_es')"""
        )).one()
        latest = conn.execute(text(
            """SELECT category, price_eur, price_date FROM mart_price_history
               WHERE series = 'es_stations'
                 AND price_date = (SELECT max(price_date) FROM mart_price_history
                                   WHERE series = 'es_stations')
               ORDER BY category"""
        )).all()

    now = datetime.now(UTC)
    fresh = {r.name: r for r in reversed(runs)}  # latest run per source
    healthy = bool(fresh) and all(
        r.status == "ok" and now - r.started_at < STALE_AFTER for r in fresh.values()
    )
    return {"runs": runs, "stations": stations, "points": points, "days": days,
            "latest": latest, "healthy": healthy, "now": now}


def _html(state: dict) -> str:
    ok = state["healthy"]
    status_color = ACCENT if ok else AMBER
    status_text = "OPERATIONAL" if ok else "STALE"
    tiles = [
        (f"{state['stations']:,}", "stations tracked"),
        (f"{state['points']:,}", "price points"),
        (f"{state['days']}", "days collected"),
        ("2005→", "EU history since"),
    ]
    tiles_html = "\n".join(
        f'<div class="tile"><div class="value">{v}</div>'
        f'<div class="label">{label}</div></div>'
        for v, label in tiles
    )
    latest_html = " · ".join(
        f'{r.category.upper()} <span class="num">{r.price_eur}</span>'
        for r in state["latest"]
    )
    latest_date = state["latest"][0].price_date if state["latest"] else "—"
    rows = "\n".join(
        f"<tr><td>{r.started_at:%Y-%m-%d %H:%M}</td><td>{r.name}</td>"
        f'<td class="{ "ok" if r.status == "ok" else "fail" }">{r.status}</td>'
        f'<td class="num">{r.items_ok:,}</td><td class="num">{r.items_failed}</td></tr>'
        for r in state["runs"]
    )
    generated = f"{state['now']:%Y-%m-%d %H:%M} UTC"

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Fuel Price Radar — status</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ margin: 0; box-sizing: border-box; }}
  body {{
    background: {PAGE}; color: {INK};
    font: 16px/1.6 -apple-system, system-ui, "Segoe UI", sans-serif;
    display: flex; justify-content: center; padding: 72px 24px;
  }}
  main {{ width: 100%; max-width: 880px; }}
  .mono {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }}
  header {{ display: flex; justify-content: space-between; align-items: baseline;
            flex-wrap: wrap; gap: 12px; }}
  h1 {{ font-size: 20px; font-weight: 600; letter-spacing: 0.04em; }}
  h1 a {{ color: inherit; text-decoration: none; }}
  .status {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
             font-size: 13px; color: {status_color}; }}
  .status::before {{ content: "●"; margin-right: 8px; }}
  h2 {{ font-size: 11px; font-weight: 600; letter-spacing: 0.18em;
        text-transform: uppercase; color: {MUTED}; margin: 64px 0 20px; }}
  .tiles {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
            gap: 12px; }}
  .tile {{ background: {SURFACE}; border: 1px solid {GRID};
           border-radius: 10px; padding: 20px; }}
  .tile .value {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
                  font-size: 26px; font-weight: 600; }}
  .tile .label {{ font-size: 13px; color: {MUTED}; margin-top: 4px; }}
  .latest {{ background: {SURFACE}; border: 1px solid {GRID}; border-radius: 10px;
             padding: 16px 20px; font-size: 14px; color: {MUTED}; }}
  .num {{ color: {INK}; font-weight: 600; }}
  img {{ width: 100%; border-radius: 10px; border: 1px solid {GRID};
         display: block; }}
  img + img {{ margin-top: 12px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ text-align: left; color: {MUTED}; font-weight: 500; padding: 8px 12px;
        border-bottom: 1px solid {GRID}; }}
  td {{ padding: 8px 12px; border-bottom: 1px solid {GRID}; }}
  td.ok {{ color: {ACCENT}; }}
  td.fail {{ color: {RED}; }}
  th:nth-child(n+4), td:nth-child(n+4) {{ text-align: right; }}
  footer {{ margin-top: 64px; font-size: 13px; color: {MUTED}; }}
  footer a {{ color: {ACCENT}; text-decoration: none; }}
</style>
</head>
<body>
<main>
  <header>
    <h1><a href="https://github.com/isistomin/fuel-price-radar">FUEL PRICE RADAR</a></h1>
    <div class="status">{status_text}</div>
  </header>

  <h2>Pipeline</h2>
  <div class="tiles">
{tiles_html}
  </div>

  <h2>Spain at the pump · {latest_date}</h2>
  <div class="latest mono">{latest_html} <span style="float:right">EUR/L · station avg</span></div>

  <h2>Charts</h2>
  <img src="img/history.png" alt="Spain pump prices, weekly since 2005">
  <img src="img/vs_eu.png" alt="G95: Spain vs EU average, last 3 years">

  <h2>Recent runs</h2>
  <table class="mono">
    <tr><th>started</th><th>source</th><th>status</th><th>ok</th><th>failed</th></tr>
{rows}
  </table>

  <footer>
    Daily ETL: Spanish stations API + EU Weekly Oil Bulletin → PostgreSQL.
    <a href="https://github.com/isistomin/fuel-price-radar">Source on GitHub</a>
    · generated {generated}
  </footer>
</main>
</body>
</html>
"""


def build(out_dir: Path) -> Path:
    engine = get_engine()
    img_dir = out_dir / "img"
    img_dir.mkdir(parents=True, exist_ok=True)
    _render_charts(engine, img_dir)
    index = out_dir / "index.html"
    index.write_text(_html(_query_state(engine)))
    return index
